services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: docker-project-frontend:latest
    container_name: momo-store-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VUE_APP_API_URL=http://backend:8081
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/momo-store/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: docker-project-backend:latest
    container_name: momo-store-backend
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8081/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true